name: pal
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOBIN: /home/runner/go/bin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.2"

      - name: Run Linters
        run: |
          make install-linters
          echo
          make lint

      - name: Build pal Binary
        run: |
          make linux
          file ./pal
          du -sh ./pal
          sha256sum ./pal
          ./pal -h

      - name: Build pal Docker Container
        run: |
          make certs
          echo
          make docker
          rm -f ./localhost.*

      - name: Run Tests Using pal Docker Container
        run: |
          make test

      - name: Run Vulnerability Scanner On Filesystem
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "fs"
          scan-ref: "."
          severity: HIGH,CRITICAL
