name: pal
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [main]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOBIN: /home/runner/go/bin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.3"

      - name: Run Linters
        run: |
          make install-deps
          echo
          make lint

      - name: Build pal Binary and Packages
        run: |
          make pkg
          file ./pal
          du -sh ./pal
          sha256sum ./pal
          ./pal -h

      - name: Run Tests Twice Using pal Docker Containers
        run: |
          make certs
          make docker
          make test && make test
          make alpine
          make test && make test
          rm -f ./localhost.*

      - name: Run Vulnerability Scanner On Filesystem
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "fs"
          scan-ref: "."
          severity: HIGH,CRITICAL
